# Generated by Django 2.0.7 on 2018-07-30 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='reuserbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserBox'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='remessage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
